config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope  '/api/v1' do
    resources :priorities
    
  end

  resources :tasks do
    patch :toggle, on: :member
  end

  get 'password', to:'passwords#edit'
  patch 'password', to:'passwords#update'
  
  get 'sign_up',  to:'registrations#new'
  post 'sign_up', to:'registrations#create'
  
  get 'sign_in',  to:'sessions#new'
  post 'sign_in', to:'sessions#create'

  get 'password/reset', to:'password_resets#new'
  post 'password/reset', to:'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  delete 'logout', to:'sessions#destroy'

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/priority.rb
class Priority < ApplicationRecord
    validates :name, presence:true
   
end

app/models/task.rb
class Task < ApplicationRecord
    
    validates :name, presence:true
    validates :desc, presence:false
    validates :due_date, presence:true
    validates :priority, presence:false
    
    def self.alphabetical
        self.all.order(:name).where(user_id: Current.user.id)
    end

    def self.date
        self.all.order(:due_date).where(user_id: Current.user.id)
    end


    has_one :priority
    belongs_to :user

    
end

app/models/user.rb
#email :string
#password_digest :string

#password :string virtual
#password_confirmation :string virtual
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true,length: { minimum: 2 },  uniqueness: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i,  message:"Must be a valid email address"}

    has_many :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be sign todo that." if Current.user.nil?
    end
    

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    
    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
            @tasks = Task.alphabetical.where(due_date: Date.today)
        end
    end
    
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new

    end
    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "We have send link reset to your email, check it out"
    end
    def edit
        @user = User.find_signed(params[:token], purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token is expired, Please try again"
    end
    def update
        @user = User.find_signed(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully, Please Sign in"
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
   before_action :require_user_logged_in!
    def edit

   end

   def update
    if Current.user.update(user_params)
        redirect_to root_path, notice:"Password Updated"
    else
        render :edit
    end

   end

   private
   def user_params
       params.require(:user).permit(:password, :password_confirmation)
   end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
    def index
        @priority = Priority.all
        render json: {
            values: @priority,
            message: "Success!"
        }, status: 200
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Succesfully created account"
        else 
            #flash[:alert] = "Something was wrong! "
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email  or Password"
            render :new

        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice:"Logged Out"
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in!
 
    # Mengubah is_done
    def toggle
        @task = Task.find(params[:id])
        if @task.is_done == true
            @task.is_done = false
            @task.save
            redirect_to tasks_path, notice: "Edited status Success"
        else
            @task.is_done = true
            @task.save
            redirect_to tasks_path, notice: "Edited status Success"
        end
    
    end

    # Menampilkan semua data tasks user    
    def index
        initializee
        handle_search
    end
    
    def initializee
        @tasks = Task.alphabetical
        #@priority = Priority.all
    end

    def handle_search
        if params[:priority].present?
            priorit = @tasks.where(priority_id:  params[:priority])

            if @priorit 
                @tasks = @tasks.where(priority_id:  params[:priority])
            else
                @tasks = @tasks.where(priority_id:  nil)
            end
        end
        if params[:due_date].present?
           
            @tasks = @tasks.where(due_date: params[:due_date])
        end    
        if params[:desc].present?
            wildcard_search = Task.sanitize_sql_like(params[:desc])
            @tasks = Task.where("name LIKE ?", "%#{wildcard_search.titleize}%")             
        end
    end

  
    # Membuat form tambah data 
    def new
        @task = Task.new 
    end

    # Mengirim data dari form tambah
    def create
        
        @task = Task.new(tasks_params)
        @task.is_done = false
        @task.user_id = session[:user_id]
        if @task.save
            redirect_to tasks_path, notice: "Created task successfully"
        else
            render :new
        end


    end

    # Menampilakn hal edit data
    def edit
        @task = Task.find(params[:id])
    end

    # Mengupdate data dari form edit
    def update
        @task = Task.find(params[:id])
        if @task.update(tasks_params)
            redirect_to tasks_path, notice: 'Task edited successfully'
        else
            render :edit   
        end
    end

    # Menghapus data
    def destroy
        @task = Task.find(params[:id])
        if @task.destroy
            redirect_to tasks_path, notice: 'Task deleted successfully'
        else
            render :index
        end
    end

    private
    def tasks_params
        params.require(:task).permit(:name, :due_date, :desc, :priority_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turboly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
 
<% if Current.user %>
<% if @tasks %>
<h1> Today Task ! - <%= Date.today.strftime("%a, %e %b %Y") %></h1>

<%= render partial: "tasks/table" %>

<% else %>
       <div class="card mt-3" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Create Task</h5>
        <p class="card-text"> </p>
        <%= link_to "Create", new_task_path, class:"btn btn-primary" %>
     
        </div>
       </div>
<% end %>

     <div class="card mt-3" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">All Task</h5>
        <p class="card-text"> </p>
        <%= link_to "Check", tasks_path, class:"btn btn-primary" %>
        </div>
    </div>
     <br>
    <div class="card mt-3" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Create Task</h5>
        <p class="card-text"> </p>
        <%= link_to "Create", new_task_path, class:"btn btn-primary" %>
        </div>
    </div>
     <br>

    

    
    <% else %>

    <div class="card mt-3" style="width: 18rem;">
        <div class="card-body">
        <% if Current.user %> 
         <h5 class="card-title">Welcome <%= Current.user.username %></h5>
        <% else %>
         <h5 class="card-title">Welcome</h5
        <% end %>
       
        <p class="card-text">lets build some task.</p>
        <%= link_to "Login", sign_in_path, class:"btn btn-primary"  %>          

        </div>
    </div>
    <% end %>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password  </h1>

<%= form_with model: @user, url:  password_reset_edit_path(token: params[:token]) do |form| %>
     
     <% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %> </div>
        <% end %>
    </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class:"form-control" , placeholder:"password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class:"form-control" , placeholder:"password confirmation" %>
    </div>
     <div class="mb-3">
        <%= form.submit "Reset Password", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password ? </h1>

<%= form_with url: password_reset_path do |form| %>
     <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control" ,placeholder:"email@turboly.com" %>
    </div>

     <div class="mb-3">
        <%= form.submit "Reset Password", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong></strong> <%= flash[:notice] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>


<% if flash[:alert]%>
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <strong></strong> <%= flash[:alert] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "TTodo", root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
         <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Tasks", tasks_path, class:"nav-link" %>
        </li>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 justify-content-end">
      <% if Current.user %> 
        <li class="nav-item">
          <%= link_to Current.user.username, password_path, class: "btn btn-outline-primary" %> 
        </li>
        <li class="nav-item">
            <%= button_to "logout", logout_path, class: "btn btn-outline-danger" ,method: :delete %>
        </li>
        <% else %>
        <li class="nav-item">
             <%= link_to "SignUp", sign_up_path, class: "btn btn-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "SignIn", sign_in_path, class: "btn btn-link" %>          
        </li>
        <% end %>
        </ul>
       
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/tasks/_search.html.erb
<%= form_tag tasks_path, method: :get do %>
        <%= text_field_tag :desc %>
        <%= date_field_tag :due_date %>
        <%= select_tag :priority, options_for_select(Priority.all.collect{|p| [p.name, p.id]}),{ include_blank: "Choose a Priority"}%>
        <%= submit_tag "Search"%>
<% end %>

<%= link_to "Clear search", tasks_path%>

app/views/tasks/_table.html.erb
<table class="table mt-3">
  <thead>
    <tr>
      <th scope="col">Task</th>
      <th scope="col">Desc</th>
      <th scope="col">Due Date</th>
      <th scope="col">Priority</th>
      <th scope="col">Status</th>
      <th scope="col"> </th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
    <tr>
    
      <td> <%= task.name %> </td>
      <td> <%= task.desc %> </td>
      <td> <%= task.due_date %></td>
    
      <%if task.priority_id == 1%>
        <td> HIGH </td>
      <%elsif task.priority_id == 2%>
        <td> low </td>
      <%elsif task.priority_id == 3%>
       <td> Medium</td>
       <%else%>
       <td> -</td>
      <% end %>
      
      <% if task.is_done %>
        <td> <%= link_to "  finish   " , toggle_task_path(task.id), method: 'patch',class: "btn btn-outline-primary" %></td>
      <% else %>
       <td> <%= link_to "Unfinished" , toggle_task_path(task.id), method: 'patch',class: "btn btn-outline-info" %></td>
      <% end%>
      
      <td> <%= link_to "Edit", edit_task_path(task.id), class: "btn btn-secondary" %></td>
      <td> 
         <%= link_to 'Remove', task_path(task.id), method: 'delete', data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      
      </td>


    </tr>
  <% end %>
  
  </tbody>
</table>

app/views/tasks/edit.html.erb
<%= link_to 'back', tasks_path %>

<%= form_with model: @task , url: task_path do |form| %>
    <% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %> </div>
        <% end %>
    </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control", placeholder:"name task" %>
    </div>
    <div class="mb-3">
        <%= form.label :desc %>
        <%= form.text_area :desc, class:"form-control" ,placeholder:"description of task" %>
    </div>
    <div class="mb-3">
        <%= form.label :due_date %>
        <%= form.date_field :due_date, class:"form-control"  %>
    </div>
    <div class="mb-3">
        <%= form.label :priority_id %>
        <%= form.select :priority_id, Priority.all.collect{|p| [p.name, p.id]},{ include_blank: "Choose a Priority"}, class:"form-select" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Update Task", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/tasks/index.html.erb
<% if @tasks %>

  <%= link_to "Create", new_task_path, class: "btn btn-primary mt-4" %>   

  <%= render partial: "tasks/search" %>
  <br />
  <br />
  data : <%= @tasks.count %> 
  <%= render partial: "tasks/table" %>

<% else %>
       <div class="card mt-3" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Create Task</h5>
        <p class="card-text"> </p>
          <%= link_to "Create", tasks_path, class:"btn btn-primary" %>
        </div>
       </div>
<% end %>

app/views/tasks/new.html.erb
<div class="mb-3" align="center">
<h1> Create Task</h1>
</div>
<%= link_to 'back', tasks_path %>

<%= form_with model: @task, url: tasks_path do |form| %>
    <% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %> </div>
        <% end %>
    </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control", placeholder:"name task" %>
    </div>
    <div class="mb-3">
        <%= form.label :desc %>
        <%= form.text_area :desc, class:"form-control" ,placeholder:"description of task" %>
    </div>
    <div class="mb-3">
        <%= form.label :due_date %>
        <%= form.date_field :due_date, class:"form-control"  %>
    </div>
    <div class="mb-3">
        <%= form.label :priority_id %>

        <%= form.select :priority_id, Priority.all.collect{|p| [p.name, p.id]},{ include_blank: "Choose a Priority"}, class:"form-select" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Create Task", class:"btn btn-primary"%>
    </div>
<% end %>